services:
  local-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=itjustworks
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  api-server:
    image: lms-public-api
    build: api/
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - local-db

  web-server:
    image: lms-web
    build: webapp/
    ports:
      - "80:80"
    depends_on:
      - api-server
